# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a72b9b942a2c02db8f77b435c76033839eab8fc7162b2662d81d22ef5defe297e1acefc26c95ab2c6fa7ce1b09e20231125213c291b065033cf9c5918703799

test:
  secret_key_base: 5ff9098df6527bb456a8d3306cc41321fac750989fbae813ab235d53be0b1be0cd35e59c2192cb6592e04a72d03301772cfc3adb5c0af511c7be2c830f7835dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
